spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: sdkf9e0324mrtf209ir2kmjf2-3049gpre34
  expiration: 3600000

server:
  ssl:
    key-store-type: JKS
    key-store: classpath:server.jks
    key-store-password: serverPass
    key-alias: server